blank_issues_enabled: false
contact_links:
  - name: "\U0001F4DA Chatbot user documentation"
    url: https://docs.chatbot.ai/getting-started/readme
    about: Documentation for users of Chatbot
  - name: "\U0001F4DA Chatbot dev documentation"
    url: https://docs.chatbot.ai/getting-started/install-self-hosted
    about: Documentation for people interested in developing and contributing for Chatbot